[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "cd /app && uvicorn api.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[volume]
mountPath = "/data"
size = "0.5"  # 500MB volume size

[[services]]
name = "hubgpt-api"
envs = [
    "ENV=production",
    "RAILWAY_RUN_UID=0",  # Ensure proper volume permissions
    "RAILWAY_VOLUME_MOUNT_PATH=/data",
    "DATABASE_URL=sqlite:////data/hubgpt.db",  # Store database in persistent volume
    "API_USERNAME=admin",
    "API_PASSWORD=password",  # Change this to a secure password
    "JWT_SECRET_KEY=your-secret-key-for-production"  # Changed to use JWT_SECRET_KEY consistently
] 